// CV of Nicolás Maire Bravo — one layout, five languages.
// Based on the original cv.typ (repo nico-maire/CV). Build all PDFs with: python3 scripts/build-cv.py
// Single language: typst compile cv/cv.typ out.pdf --input lang=es

#let lang = sys.inputs.at("lang", default: "en")

#set page(paper: "a4", margin: 1.5cm)
#set text(
  // The published CV uses Libertinus Serif (Typst's default); CJK falls back to a system font.
  font: ("Libertinus Serif", "Noto Serif CJK SC", "Noto Sans CJK SC", "WenQuanYi Zen Hei"),
  fallback: true,
  size: 10pt,
  lang: if lang == "zh" { "zh" } else { lang },
)

// ---------------------------------------------------------------- texts
#let T = (
  en: (
    title: [Computer Science Student | Developer \ & AI/Cybersecurity Enthusiast | Entrepreneur],
    summary-h: "Professional Summary",
    summary: [Computer Science student at UC3M, awarded exchange semesters at the Università di Bologna (Italy) and UADE (Argentina). I have a strong dual focus on Artificial Intelligence and Cybersecurity, but I really enjoy every discipline. Passionate about building my own tools and exploring complex architectures. I believe in turning ideas into reality, and entrepreneurship is what I think about most.],
    skills-h: "Technical Skills",
    sk-lang: "Languages:", sk-ai: "AI, IoT & Cybersecurity:", sk-tools: "Tools & Frameworks:", sk-sys: "Systems & DevOps:",
    sk-ai-list: "PyTorch, Transformers, MQTT, Raspberry Pi, Jupyter, Security Protocols",
    sk-sys-list: "Git, Linux, Docker, TCP/UDP Sockets, POSIX",
    langs-h: "Languages",
    langs: (("Spanish", "Native"), ("English", "C1 Advanced (Cambridge)"), ("Chinese", "HSK3 (studied up to HSK5)"), ("French", "Intermediate"), ("Italian", "Advanced")),
    about-h: "About Me",
    about: [Charismatic, punctual and organised. I am a fast learner with a strong dedication to improvement. I adapt easily to new environments, excel at working in a team, and thrive when solving low-level or complex architectural problems.],
    exp-h: "Experience (Entrepreneurial)",
    cs-role: "Founder & Full-Stack Developer", present: "Present",
    cs-1: [Founded and developed a B2B SaaS platform that digitises local salons and businesses, streamlining workflows and appointment scheduling.],
    via-role: "Lead Developer & Automation Architect",
    via-1: [Architected the full-stack "VIA" platform (React/FastAPI).],
    via-2: [Engineered backend automation services connecting n8n workflows with custom Python scripts and Hugging Face models.],
    agb-details: "Python, AI Agents, Visual Interface",
    agb-1: [Developed a personal tool that uses interconnected AI agents to analyse business logic and auto-generate complex automation workflows.],
    edu-h: "Education & Certifications",
    degree: "B.Sc. in Computer Science (Bilingual Programme)",
    edu-1: [*Erasmus+ Exchange:* Università di Bologna (UniBO), Italy | Feb 2026 – Jun 2026.],
    edu-2: [*International Mobility:* UADE (Buenos Aires, Argentina) | Jul 2026 – Dec 2026.],
    edu-3: [Santander Grant awarded for academic record.],
    proj-h: "Academic & Technical Projects",
    p-ml: "ML: Neural Calculator & Generalisation Engine",
    p-ml-1: [Designed and trained Seq2Seq/Transformer models at UniBO to evaluate structural and out-of-distribution (OOD) generalisation.],
    p-ds: "Distributed Minesweeper: Fault-Tolerant SMR",
    p-ds-1: [Built a fault-tolerant multiplayer game using a Replicated State Machine (SMR) architecture, Leader–Follower topology and two-phase commit.],
    p-sec: "LLM Security & RAG Encryption Engines",
    p-sec-1: [Researched LLM vulnerabilities through PoCs, mitigating prompt injection with ML-based guardrails.],
    p-sec-2: [Built an envelope encryption (KMS/DEK/KEK) architecture for RAG databases.],
    p-iot: "Atlas IoT IDE & Smart Space Orchestration",
    p-iot-1: [Built a web-based visual IDE to dynamically discover (via UDP multicast) and program distributed IoT devices through a node-based interface.],
    p-rt: "Performance-Oriented Ray Tracing",
    p-rt-1: [Optimised a 3D ray-tracing application by implementing and comparing memory representation strategies (SOA vs. AOS).],
    p-astar: "Heuristic Search (A*)",
    p-astar-1: [Developed a route-planning system for a spy plane using the A\* algorithm and admissible heuristics over a cost map generated by Gaussian radar models.],
    p-mario: "Mario Bros. Arcade Clone",
    p-mario-d: "Python, Pyxel, Object-Oriented Programming",
    p-mario-1: [Recreated the classic arcade game, engineering a complex OOP architecture from scratch to manage physics, collision detection and enemy AI logic.],
    contact-h: "Contact",
    portfolio: "Portfolio",
  ),
  es: (
    title: [Estudiante de Ingeniería Informática | Desarrollo de software \ IA y Ciberseguridad | Emprendimiento],
    summary-h: "Resumen profesional",
    summary: [Estudiante de Ingeniería Informática en la UC3M, con estancias de intercambio en la Università di Bologna (Italia) y en la UADE (Argentina). Mi foco principal está en la Inteligencia Artificial y la Ciberseguridad, aunque disfruto de cada disciplina. Me apasiona construir mis propias herramientas y explorar arquitecturas complejas. Creo en convertir las ideas en realidad, y emprender es en lo que más pienso.],
    skills-h: "Habilidades técnicas",
    sk-lang: "Lenguajes:", sk-ai: "IA, IoT y Ciberseguridad:", sk-tools: "Herramientas y frameworks:", sk-sys: "Sistemas y DevOps:",
    sk-ai-list: "PyTorch, Transformers, MQTT, Raspberry Pi, Jupyter, protocolos de seguridad",
    sk-sys-list: "Git, Linux, Docker, sockets TCP/UDP, POSIX",
    langs-h: "Idiomas",
    langs: (("Español", "Nativo"), ("Inglés", "C1 Advanced (Cambridge)"), ("Chino", "HSK3 (estudiado hasta HSK5)"), ("Francés", "Intermedio"), ("Italiano", "Alto")),
    about-h: "Sobre mí",
    about: [Me definen el carisma, la puntualidad y la organización. Aprendo rápido y tengo muchas ganas de mejorar. Me adapto con facilidad a entornos nuevos, trabajo muy bien en equipo y disfruto resolviendo problemas de bajo nivel o de arquitectura compleja.],
    exp-h: "Experiencia (emprendimiento)",
    cs-role: "Fundación y desarrollo full-stack", present: "Actualidad",
    cs-1: [Fundé y desarrollo una plataforma SaaS B2B que digitaliza peluquerías y negocios locales, agilizando su día a día y la gestión de citas.],
    via-role: "Desarrollo principal y arquitectura de automatización",
    via-1: [Diseñé la plataforma full-stack "VIA" (React/FastAPI).],
    via-2: [Desarrollé servicios de automatización en el backend que conectan flujos de n8n con scripts propios en Python y modelos de Hugging Face.],
    agb-details: "Python, agentes de IA, interfaz visual",
    agb-1: [Desarrollé una herramienta propia que usa agentes de IA interconectados para analizar la lógica de un negocio y generar automáticamente flujos de automatización complejos.],
    edu-h: "Formación y certificados",
    degree: "Grado en Ingeniería Informática (programa bilingüe)",
    edu-1: [*Intercambio Erasmus+:* Università di Bologna (UniBO), Italia | feb 2026 – jun 2026.],
    edu-2: [*Movilidad internacional:* UADE (Buenos Aires, Argentina) | jul 2026 – dic 2026.],
    edu-3: [Beca Santander por expediente académico.],
    proj-h: "Proyectos académicos y técnicos",
    p-ml: "ML: calculadora neuronal y motor de generalización",
    p-ml-1: [Diseñé y entrené modelos Seq2Seq/Transformer en la UniBO para evaluar su generalización estructural y fuera de distribución (OOD).],
    p-ds: "Buscaminas distribuido: SMR tolerante a fallos",
    p-ds-1: [Construí un juego multijugador tolerante a fallos con una máquina de estados replicada (SMR), topología Líder-Seguidor y commit en dos fases.],
    p-sec: "Seguridad en LLM y cifrado de bases RAG",
    p-sec-1: [Investigué vulnerabilidades de los LLM mediante pruebas de concepto, mitigando la inyección de prompts con guardarraíles basados en ML.],
    p-sec-2: [Construí una arquitectura de cifrado de sobre (KMS/DEK/KEK) para bases de datos RAG.],
    p-iot: "Atlas IoT IDE y orquestación de Smart Spaces",
    p-iot-1: [Construí un IDE visual web para descubrir (mediante UDP multicast) y programar dispositivos IoT distribuidos con una interfaz de nodos.],
    p-rt: "Ray tracing orientado al rendimiento",
    p-rt-1: [Optimicé una aplicación de ray tracing 3D implementando y comparando estrategias de representación en memoria (SOA frente a AOS).],
    p-astar: "Búsqueda heurística (A*)",
    p-astar-1: [Desarrollé un planificador de rutas para un avión espía con el algoritmo A\* y heurísticas admisibles, sobre un mapa de costes generado por modelos gaussianos de radar.],
    p-mario: "Clon del arcade Mario Bros.",
    p-mario-d: "Python, Pyxel, programación orientada a objetos",
    p-mario-1: [Recreé el clásico arcade con una arquitectura orientada a objetos desde cero para gestionar la física, las colisiones y la IA de los enemigos.],
    contact-h: "Contacto",
    portfolio: "Portfolio",
  ),
  it: (
    title: [Studente di Ingegneria Informatica | Sviluppo software \ IA e Cybersecurity | Imprenditorialità],
    summary-h: "Profilo professionale",
    summary: [Studio Ingegneria Informatica all'UC3M, con periodi di scambio all'Università di Bologna (Italia) e all'UADE (Argentina). Mi concentro soprattutto su Intelligenza Artificiale e Cybersecurity, ma mi appassiona ogni disciplina. Amo costruire i miei strumenti ed esplorare architetture complesse. Credo nel trasformare le idee in realtà, e fare impresa è ciò a cui penso di più.],
    skills-h: "Competenze tecniche",
    sk-lang: "Linguaggi:", sk-ai: "IA, IoT e Cybersecurity:", sk-tools: "Strumenti e framework:", sk-sys: "Sistemi e DevOps:",
    sk-ai-list: "PyTorch, Transformers, MQTT, Raspberry Pi, Jupyter, protocolli di sicurezza",
    sk-sys-list: "Git, Linux, Docker, socket TCP/UDP, POSIX",
    langs-h: "Lingue",
    langs: (("Spagnolo", "Madrelingua"), ("Inglese", "C1 Advanced (Cambridge)"), ("Cinese", "HSK3 (studiato fino all'HSK5)"), ("Francese", "Intermedio"), ("Italiano", "Avanzato")),
    about-h: "Chi sono",
    about: [Carisma, puntualità e organizzazione mi contraddistinguono. Imparo in fretta e ho una forte voglia di migliorare. Mi adatto facilmente ai nuovi ambienti, lavoro molto bene in squadra e do il meglio con problemi di basso livello o di architettura complessa.],
    exp-h: "Esperienza (imprenditoriale)",
    cs-role: "Fondazione e sviluppo full-stack", present: "Oggi",
    cs-1: [Ho fondato e sviluppo una piattaforma SaaS B2B che digitalizza parrucchieri e attività locali, semplificando il lavoro quotidiano e la gestione degli appuntamenti.],
    via-role: "Sviluppo principale e architettura dell'automazione",
    via-1: [Ho progettato la piattaforma full-stack "VIA" (React/FastAPI).],
    via-2: [Ho sviluppato servizi di automazione backend che collegano flussi n8n con script Python personalizzati e modelli di Hugging Face.],
    agb-details: "Python, agenti IA, interfaccia visuale",
    agb-1: [Ho sviluppato uno strumento personale che usa agenti IA interconnessi per analizzare la logica di business e generare automaticamente flussi di automazione complessi.],
    edu-h: "Formazione e certificati",
    degree: "Laurea in Ingegneria Informatica (corso bilingue)",
    edu-1: [*Scambio Erasmus+:* Università di Bologna (UniBO), Italia | feb 2026 – giu 2026.],
    edu-2: [*Mobilità internazionale:* UADE (Buenos Aires, Argentina) | lug 2026 – dic 2026.],
    edu-3: [Borsa di studio Santander per merito accademico.],
    proj-h: "Progetti accademici e tecnici",
    p-ml: "ML: calcolatrice neurale e generalizzazione",
    p-ml-1: [Ho progettato e addestrato modelli Seq2Seq/Transformer all'UniBO per valutarne la generalizzazione strutturale e fuori distribuzione (OOD).],
    p-ds: "Campo minato distribuito: SMR tollerante ai guasti",
    p-ds-1: [Ho costruito un gioco multigiocatore tollerante ai guasti con una macchina a stati replicata (SMR), topologia Leader–Follower e commit a due fasi.],
    p-sec: "Sicurezza degli LLM e cifratura di database RAG",
    p-sec-1: [Ho studiato le vulnerabilità degli LLM con proof of concept, mitigando la prompt injection con guardrail basati su ML.],
    p-sec-2: [Ho costruito un'architettura di envelope encryption (KMS/DEK/KEK) per database RAG.],
    p-iot: "Atlas IoT IDE e orchestrazione di Smart Space",
    p-iot-1: [Ho costruito un IDE visuale web per scoprire (via UDP multicast) e programmare dispositivi IoT distribuiti con un'interfaccia a nodi.],
    p-rt: "Ray tracing orientato alle prestazioni",
    p-rt-1: [Ho ottimizzato un'applicazione di ray tracing 3D implementando e confrontando strategie di rappresentazione in memoria (SOA e AOS).],
    p-astar: "Ricerca euristica (A*)",
    p-astar-1: [Ho sviluppato un pianificatore di rotte per un aereo spia con l'algoritmo A\* ed euristiche ammissibili, su una mappa dei costi generata da modelli radar gaussiani.],
    p-mario: "Clone dell'arcade Mario Bros.",
    p-mario-d: "Python, Pyxel, programmazione a oggetti",
    p-mario-1: [Ho ricreato il classico arcade con un'architettura a oggetti costruita da zero per gestire fisica, collisioni e IA dei nemici.],
    contact-h: "Contatti",
    portfolio: "Portfolio",
  ),
  fr: (
    title: [Études d'informatique | Développement logiciel \ IA et cybersécurité | Entrepreneuriat],
    summary-h: "Profil professionnel",
    summary: [J'étudie l'informatique à l'UC3M, avec des échanges à l'Università di Bologna (Italie) et à l'UADE (Argentine). Je me concentre sur l'IA et la cybersécurité, sans négliger aucune discipline. J'aime créer mes propres outils et explorer des architectures complexes. Je crois qu'il faut transformer les idées en réalité ; l'entrepreneuriat est ce qui me motive le plus.],
    skills-h: "Compétences techniques",
    sk-lang: "Langages :", sk-ai: "IA, IoT et cybersécurité :", sk-tools: "Outils et frameworks :", sk-sys: "Systèmes et DevOps :",
    sk-ai-list: "PyTorch, Transformers, MQTT, Raspberry Pi, Jupyter, protocoles de sécurité",
    sk-sys-list: "Git, Linux, Docker, sockets TCP/UDP, POSIX",
    langs-h: "Langues",
    langs: (("Espagnol", "Langue maternelle"), ("Anglais", "C1 Advanced (Cambridge)"), ("Chinois", "HSK3 (étudié jusqu'au HSK5)"), ("Français", "Intermédiaire"), ("Italien", "Avancé")),
    about-h: "À propos",
    about: [Charisme, ponctualité et organisation me caractérisent. J'apprends vite et j'ai une forte envie de progresser. Je m'adapte facilement à de nouveaux environnements, je travaille très bien en équipe et je donne le meilleur de moi-même face aux problèmes bas niveau ou d'architecture complexe.],
    exp-h: "Expérience (entrepreneuriale)",
    cs-role: "Fondation et développement full-stack", present: "Aujourd'hui",
    cs-1: [Fondation et développement d'une plateforme SaaS B2B qui numérise les salons de coiffure et commerces de proximité, en simplifiant leur quotidien et la gestion des rendez-vous.],
    via-role: "Développement principal et architecture de l'automatisation",
    via-1: [Conception de la plateforme full-stack « VIA » (React/FastAPI).],
    via-2: [Développement de services d'automatisation backend reliant des workflows n8n à des scripts Python sur mesure et à des modèles Hugging Face.],
    agb-details: "Python, agents IA, interface visuelle",
    agb-1: [Développement d'un outil personnel utilisant des agents IA interconnectés pour analyser la logique métier et générer automatiquement des workflows d'automatisation complexes.],
    edu-h: "Formation et certificats",
    degree: "Licence en informatique (cursus bilingue)",
    edu-1: [*Échange Erasmus+ :* Università di Bologna (UniBO), Italie | févr. 2026 – juin 2026.],
    edu-2: [*Mobilité internationale :* UADE (Buenos Aires, Argentine) | juil. 2026 – déc. 2026.],
    edu-3: [Bourse Santander obtenue pour le dossier académique.],
    proj-h: "Projets académiques et techniques",
    p-ml: "ML : calculatrice neuronale et généralisation",
    p-ml-1: [Conception et entraînement de modèles Seq2Seq/Transformer à l'UniBO pour évaluer leur généralisation structurelle et hors distribution (OOD).],
    p-ds: "Démineur distribué : SMR tolérante aux pannes",
    p-ds-1: [Jeu multijoueur tolérant aux pannes fondé sur une machine à états répliquée (SMR), une topologie Leader–Follower et un commit en deux phases.],
    p-sec: "Sécurité des LLM et chiffrement de bases RAG",
    p-sec-1: [Étude des vulnérabilités des LLM par des preuves de concept, en atténuant l'injection de prompt avec des garde-fous basés sur le ML.],
    p-sec-2: [Conception d'une architecture de chiffrement d'enveloppe (KMS/DEK/KEK) pour bases de données RAG.],
    p-iot: "Atlas IoT IDE et orchestration de Smart Spaces",
    p-iot-1: [IDE visuel web pour découvrir (par UDP multicast) et programmer des objets IoT distribués grâce à une interface à nœuds.],
    p-rt: "Ray tracing orienté performance",
    p-rt-1: [Optimisation d'une application de ray tracing 3D en implémentant et comparant des stratégies de représentation mémoire (SOA et AOS).],
    p-astar: "Recherche heuristique (A*)",
    p-astar-1: [Planificateur d'itinéraires pour un avion espion avec l'algorithme A\* et des heuristiques admissibles, sur une carte de coûts générée par des modèles radar gaussiens.],
    p-mario: "Clone de l'arcade Mario Bros.",
    p-mario-d: "Python, Pyxel, programmation orientée objet",
    p-mario-1: [Recréation du jeu d'arcade classique avec une architecture orientée objet conçue de zéro pour gérer la physique, les collisions et l'IA des ennemis.],
    contact-h: "Contact",
    portfolio: "Portfolio",
  ),
  zh: (
    title: [计算机科学学生 | 软件开发 \ 人工智能与网络安全 | 创业],
    summary-h: "个人简介",
    summary: [马德里卡洛斯三世大学（UC3M）计算机科学专业学生，曾获得博洛尼亚大学（意大利）和 UADE（阿根廷）的交换学习机会。我主要专注于人工智能和网络安全，同时也热爱每一个技术方向。我热衷于打造自己的工具、探索复杂的系统架构。我相信要把想法变成现实，而创业是我最常思考的事情。],
    skills-h: "专业技能",
    sk-lang: "编程语言：", sk-ai: "人工智能、物联网与网络安全：", sk-tools: "工具与框架：", sk-sys: "系统与 DevOps：",
    sk-ai-list: "PyTorch、Transformers、MQTT、树莓派、Jupyter、安全协议",
    sk-sys-list: "Git、Linux、Docker、TCP/UDP 套接字、POSIX",
    langs-h: "语言能力",
    langs: (("西班牙语", "母语"), ("英语", "C1 Advanced（剑桥）"), ("汉语", "HSK3（学习至 HSK5）"), ("法语", "中级"), ("意大利语", "高级")),
    about-h: "关于我",
    about: [外向、守时、有条理。学习能力强，始终追求进步。能快速适应新环境，善于团队合作，尤其擅长解决底层或复杂架构问题。],
    exp-h: "创业经历",
    cs-role: "创始人兼全栈开发者", present: "至今",
    cs-1: [创办并开发了一个 B2B SaaS 平台，帮助美发店和本地商家实现数字化，简化日常工作和预约管理。],
    via-role: "首席开发者兼自动化架构师",
    via-1: [设计了全栈平台“VIA”（React/FastAPI）。],
    via-2: [开发后端自动化服务，将 n8n 工作流与自定义 Python 脚本和 Hugging Face 模型连接起来。],
    agb-details: "Python、AI 智能体、可视化界面",
    agb-1: [开发了一款个人工具，利用多个互联的 AI 智能体分析业务逻辑，并自动生成复杂的自动化工作流。],
    edu-h: "教育背景与证书",
    degree: "计算机科学学士（双语项目）",
    edu-1: [*伊拉斯谟+ 交换项目：* 博洛尼亚大学（UniBO），意大利 | 2026 年 2 月 – 2026 年 6 月。],
    edu-2: [*国际交换：* UADE（阿根廷布宜诺斯艾利斯） | 2026 年 7 月 – 2026 年 12 月。],
    edu-3: [因学业成绩优异获得桑坦德奖学金。],
    proj-h: "学术与技术项目",
    p-ml: "机器学习：神经计算器与泛化研究",
    p-ml-1: [在博洛尼亚大学设计并训练 Seq2Seq/Transformer 模型，评估其结构泛化和分布外（OOD）泛化能力。],
    p-ds: "分布式扫雷：容错状态机复制",
    p-ds-1: [基于复制状态机（SMR）、主从拓扑和两阶段提交，构建了一款容错多人游戏。],
    p-sec: "大语言模型安全与 RAG 数据库加密",
    p-sec-1: [通过概念验证研究大语言模型漏洞，并用基于机器学习的防护栏缓解提示词注入。],
    p-sec-2: [为 RAG 数据库构建了信封加密（KMS/DEK/KEK）架构。],
    p-iot: "Atlas IoT IDE 与智能空间编排",
    p-iot-1: [开发了基于 Web 的可视化 IDE，通过 UDP 组播动态发现分布式物联网设备，并以节点界面进行编程。],
    p-rt: "面向性能的光线追踪",
    p-rt-1: [通过实现并比较内存表示策略（SOA 与 AOS），优化了一个 3D 光线追踪应用。],
    p-astar: "启发式搜索（A*）",
    p-astar-1: [使用 A\* 算法和可采纳启发函数，在由高斯雷达模型生成的代价地图上为侦察机规划航线。],
    p-mario: "《马里奥兄弟》街机复刻",
    p-mario-d: "Python、Pyxel、面向对象编程",
    p-mario-1: [从零构建复杂的面向对象架构，重制经典街机游戏，处理物理、碰撞检测和敌人 AI 逻辑。],
    contact-h: "联系方式",
    portfolio: "作品集",
  ),
).at(lang)

// ---------------------------------------------------------------- helpers (from the original CV)
#let section_title(title) = {
  text(size: 14pt, weight: "bold")[#title]
  v(-0.3em)
  line(length: 100%, stroke: 0.5pt)
  v(0.5em)
}

#let contact_link_img(icon_path, text_link, href) = {
  grid(
    columns: (auto, 1fr),
    column-gutter: 0.5em,
    align: (center + horizon, left + horizon),
    image(icon_path, width: 16pt),
    link(href)[#text_link]
  )
}

#let entry(title, details, date, body) = {
  grid(
    columns: (1fr, auto),
    align: (left, right),
    [
      #text(weight: "bold")[#title] \
      #text(style: "italic", size: 9pt)[#details]
    ],
    text(style: "italic", size: 9pt)[#date]
  )
  v(0.3em)
  body
  v(0.8em)
}

// ---------------------------------------------------------------- CV
#columns(2, gutter: 1cm)[

  #align(center)[#text(size: 24pt, weight: "bold")[Nicolás Maire Bravo]]
  #v(0.5em)

  #align(center)[
    #box(clip: true, radius: 50%, width: 100pt, image("assets/profile.jpg", width: 100%))
  ]
  #v(0.5em)

  #align(center)[#text(size: 11pt)[#T.title]]
  #v(0.7em)

  #section_title(T.summary-h)
  #T.summary
  #v(0.7em)

  #section_title(T.skills-h)

  #text(weight: "bold")[#T.sk-lang]
  #v(0.2em)
  Python, C, C++, JavaScript, TypeScript, SQL, R, HTML/CSS
  #v(0.45em)

  #text(weight: "bold")[#T.sk-ai]
  #v(0.2em)
  #T.sk-ai-list
  #v(0.45em)

  #text(weight: "bold")[#T.sk-tools]
  #v(0.2em)
  React, Next.js, FastAPI, Supabase, n8n, Hugging Face, Celonis, Flutter
  #v(0.45em)

  #text(weight: "bold")[#T.sk-sys]
  #v(0.2em)
  #T.sk-sys-list
  #v(0.7em)

  #section_title(T.langs-h)
  #grid(
    columns: (1fr, auto),
    row-gutter: 0.4em,
    column-gutter: 0.5em,
    ..T.langs.map(((name, level)) => ([#name], [#level])).flatten()
  )
  #v(0.9em)

  // ---- right column
  #colbreak()
  #section_title(T.exp-h)

  #entry("CitaSalon.online (SaaS Platform)", T.cs-role, [2026 – #T.present], [- #T.cs-1])

  #entry("VIA Project (VisiónIAutomatización)", T.via-role, "2025 – 2026", [
    - #T.via-1
    - #T.via-2
  ])

  #entry("AI Agent Automation Builder", T.agb-details, "2025", [- #T.agb-1])

  #section_title(T.edu-h)

  #entry(T.degree, "Universidad Carlos III de Madrid (UC3M)", [2023 – #T.present], [
    - #T.edu-1
    - #T.edu-2
    - #T.edu-3
  ])

  #section_title(T.proj-h)

  #entry(T.p-ml, "Python, PyTorch, Transformers, Deep Learning", "2026", [- #T.p-ml-1])
  #entry(T.p-ds, "Python, Distributed Systems, TCP Sockets, Docker", "2026", [- #T.p-ds-1])
  #entry(T.p-sec, "Python, Cybersecurity, Prompt Injection, AES-GCM", "2026", [
    - #T.p-sec-1
    - #T.p-sec-2
  ])
  #entry(T.p-iot, "Python, JavaScript, WebSockets, UDP/TCP, IoT", "2026", [- #T.p-iot-1])
  #entry(T.p-rt, "C++23, Intel TBB, Performance, AOS/SOA", "2025", [- #T.p-rt-1])
  #entry(T.p-astar, "Python, A*, AI", "2024", [- #T.p-astar-1])
  #entry(T.p-mario, T.p-mario-d, "2023", [- #T.p-mario-1])

  #section_title(T.about-h)
  #T.about
  #v(1em)

  #section_title(T.contact-h)
  #contact_link_img("assets/email.png", "nico.maibra@gmail.com", "mailto:nico.maibra@gmail.com")
  #v(0.4em)
  #contact_link_img("assets/linkedin.png", "linkedin.com/in/nicolás-maire-bravo", "https://www.linkedin.com/in/nicol%C3%A1s-maire-bravo/")
  #v(0.4em)
  #contact_link_img("assets/github.png", "github.com/nico-maire", "https://github.com/nico-maire")
  #v(0.4em)
  #link("https://nico-maire.github.io/")[#T.portfolio: nico-maire.github.io]
]
