// Regenerates js/core/brands.js with the monochrome brand logos used by the site.
// Usage: npm install simple-icons (anywhere) && NODE_PATH=<that>/node_modules node scripts/build-brands.mjs
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';

const require = createRequire(import.meta.url);
const si = require('simple-icons');

// site id -> simple-icons export name
const WANT = {
  python: 'siPython', c: 'siC', cplusplus: 'siCplusplus', javascript: 'siJavascript',
  typescript: 'siTypescript', r: 'siR', html5: 'siHtml5', css: 'siCss', react: 'siReact',
  nextjs: 'siNextdotjs', tailwindcss: 'siTailwindcss', fastapi: 'siFastapi', flask: 'siFlask',
  supabase: 'siSupabase', postgresql: 'siPostgresql', mysql: 'siMysql', sqlite: 'siSqlite',
  pytorch: 'siPytorch', huggingface: 'siHuggingface', jupyter: 'siJupyter', numpy: 'siNumpy',
  pandas: 'siPandas', opencv: 'siOpencv', n8n: 'siN8n', linux: 'siLinux', git: 'siGit',
  github: 'siGithub', docker: 'siDocker', bash: 'siGnubash', cmake: 'siCmake',
  raspberrypi: 'siRaspberrypi', mqtt: 'siMqtt', socketio: 'siSocketdotio', typst: 'siTypst',
  flutter: 'siFlutter', youtube: 'siYoutube', gmail: 'siGmail', intel: 'siIntel',
};

const out = {};
for (const [id, key] of Object.entries(WANT)) {
  const icon = si[key];
  if (!icon) { console.warn('missing', key); continue; }
  out[id] = { title: icon.title, path: icon.path };
}

const src = `// Generated by scripts/build-brands.mjs from Simple Icons (CC0). Do not edit by hand.
export const BRANDS = ${JSON.stringify(out, null, 0).replace(/},"/g, '},\n  "')};

export function brandSvg(id) {
  const b = BRANDS[id];
  return b ? \`<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="\${b.path}"/></svg>\` : '';
}
`;
writeFileSync(new URL('../js/core/brands.js', import.meta.url), src);
console.log('wrote', Object.keys(out).length, 'brands');
